name: jive_app
description: "Jive App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  rust: ^3.0.0
  anyhow: ^3.0.1
  logger: ^2.5.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  auto_route: ^9.2.2
  auto_route_generator: ^9.0.0
  catppuccin_flutter: ^1.0.0
  shared_preferences: ^2.3.3
  web_socket_channel: ^3.0.1
  spotify_sdk: ^3.0.2
  flutter_dotenv: ^5.2.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  uuid: ^4.5.1
  youtube_explode_dart: ^2.3.6
  async: ^2.11.0
  reorderables: ^0.6.0
  collection: ^1.19.0
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  pretty_qr_code: ^3.3.0
  share_plus: ^10.1.3
  mobile_scanner: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  riverpod_generator: ^2.6.3
  shared_preferences_tools: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/logos/
